name: acadrepro

services:
  acadrepro:
    image: acadrepro:latest
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBIAN_MIRROR: https://mirrors.tuna.tsinghua.edu.cn
        PYPI_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
        NPM_REGISTRY: https://registry.npmmirror.com
    container_name: acadrepro
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
